>WP_086041869.1_136_311_UG5_
----------------------------------------------YANRLNKNSNAFFK
YFYSEYINYRNDAFQAMEQIVDNKK-EGLLIQKDITKCYDNIDLK-----YLKN------
KV---NQY--LTKDKEK----YYREINEVIFAVI---DIYNEM----------------L
EGNTY---LPFGFLPSGILVNLYFENLDNMIIDEFNPISYGRYVDDITFIIRKD---FEN
EYEKKINRVNEKIELIKDKFNEDKEIKF--------------------------------
---------
>WP_092560583.1_188_305_UG5_
------------------------------------------------------------
---------------------CKNE-NTVMISLDLKSFYYYIDFD-----FRDFA-----
KLFNNDERYTKIEFITS----IISDIYTKYTELV---VKYKKG-IKK-------------
--SVGKSVFPIGLISPLILRDIALEGVDNSIKKGLSPKYYGRYVDDMLIVVGT-------
------------------------------------------------------------
---------
>WP_073442822.1_180_309_UG5_
------------------------------------------------------------
------------AFRSLEDNYENHQ-NSVLISLDLKSYYYSVKFS-----FASL------
RKHLSQQILRKLKNLSL----IQEKIYLRYKEIL---SLYNRDIKGF-------------
--NSNEYPLPLGLFSSMILANLYLTDFDKDVRSLNAISYYGRYVDDMLFVFNDS---VQ-
------------------------------------------------------------
---------
>WP_073291237.1_187_363_UG5_
------------------------------------------------------------
--------------SIYATEKNIKK-DTALVSLDIKSYYYTVNFK-----FRELL-----
VILQNDENLIKIEKLTY----IIEQIYVKYTGIL---SEFREVLQDY-------------
--KKQEVLLPIGTFSSMLIANLYLSEFDNSMKNNKKVLYYGRYVDDMLILLDVS---ADK
KVDKNIIIDDYLVEKNKILDKVKENKYCIHKLDNLIIQKDKVKIIYL-------------
---------
>WP_089736954.1_207_333_UG5_
------------------------------------------------------------
-------------IIVAQNLLNNEK-NALFINLDIKDYFHSCRVS-------LD------
RYFNIDNE--NFNCINY----ILRKIHVIYSNLIAKKHKFPYDFSPE------------L
ESKSL---IPIGLLSSYVIANHYLNDFDKIITNKFKPAYYGRYVDDILIVLSEPN-----
------------------------------------------------------------
---------
>WP_090882977.1_107_326_UG5_
--IDFRIISNLTVDFHVISSLWIDHFAYEIELKLSENSYGSRLNASGFHP--SAETNHFR
AYIHDYRKWQKKGLDAIKEKMDDTD-ELVALTADIKSFYHNIDVS-----FLAS------
ESFFKSFM--PRIYLSQ----RQKYLNNLLIKAI---SYWSEH-CYSNLTQKTKES-FNG
QGHVG---IPIGLSASKVIANLVLKEFDEAIEQELMPLYYGRYVDDIFLVLGKN---KKI
TGRESMWDYICER-----------------------------------------------
---------
>WP_061524151.1_175_371_UG5_
------------------------------------------------------KNTSFQ
PYFLPYKEWQNNGLNSIEKSLEAKK-NVMVFSLDLKGYYHNIDAK-----IISN------
DNFNSDI---GVE-LDD----SEKKFNLIICNLI---DRWGDD-VTEYYKLK-----FNF
DLKAG---LPIGLTCSKIISNIVLKILDDKIEGNLKPISYGRYVDDIFIVVDN----KDF
LNKKDFLRFFANKIGIDDIKNINDILGKYKTKTELKVQDKKIKTFFL-------------
---------
>CQH54232.1_171_324_UG5_
----------------------------------------------------LNSLGSFQ
PYFEPYKKWRNQGLQSIRKELEEDH-AVIAVSMDLTSYYHRIDPS-----FMKN------
KSFLAES---NIE-LSK----WELEFTTAYSLAL---QNWSKI-VKE--RMHQFGCSKKE
VNIGG---LPIGLSISRILSNVLLLGLDRDIEQGLTPIYYGRYVDDIFLVIKDP---L--
------------------------------------------------------------
---------
>WP_025510150.1_201_326_UG5_
------------------------------------------------------------
---------------------EHNR-SVVAVSLDLKSYYHNIDPS-----FIGE------
KSFLETIGLCGSNSLSE----NEIKLTKKLSSLL---VKWNKE-ATEYTKTLSD---SKS
NVACG---LAIGLTASRVISNVLLWRWDKLIRQELTPVHYGRYVDDMFLVLND-------
------------------------------------------------------------
---------
>YP_736403.1_UG5_250_328
------------------------------------------------------------
------------------------------------------------------------
---------------------------EQLSKFL---SNWAEE-ASE-FGKTVGGK-KAK
IN-GG---LVIGLTCSRIISNALLYKWDRLVLEKLSPVHYGRYVDDMFLVLRDT---GT-
------------------------------------------------------------
---------
>WP_021437228.1_189_350_UG5_
------------------------------------------------------------
-------------LKVIRDNLHKNR-NVIAASLDLENFFHNIDPS-----FLSS------
EAFVKELIGKSLIGLSE----DETKFNVQMSQFL---KRWSDKASSLF---------DKS
FFNGG---LVVGLTATRVISNIILYKFDKLVKEKITPIHYGRYVDDLFLVILDP---GNV
RNIVEFMDYLKNRLGNGYLSNNKDKWSIN-------------------------------
---------
>WP_084811756.1_184_302_UG5_
------------------------------------------------------------
--------------------LDDRK-SVIALTADVTSYYHCLNPE-----FLLD------
KYFLHGVL--GAD-LDT----QETKLHRLFVKSL---VWWSHN-VAE----------RTG
WRPRG---LPVGLPASAVVANLALIQLDEVISDEVKPLYYGRYVDDILLVLEDS---G--
------------------------------------------------------------
---------
>WP_099323523.1_185_305_UG5_
------------------------------------------------------------
-------------------ALEHEK-SVVAITADVTSFYHKLDVR-----FMLN------
DHFIKRI---GVE-LDN----DEKKLHSLFITAL---YQWAKK-TPL-------------
--KRG---LPVGLTASSVIANVALFELDGLFEREIVPLYYGRYVDDIILVMENG---ANF
KRSVE-------------------------------------------------------
---------
>WP_089978274.1_195_304_UG5_
------------------------------------------------------------
---------------------SEGK-KVAALTADVSSFYHELQPD-----FLLD------
KSFN-ELL--GVS-LDA----AESKLHRIFVSAL---RQWGAK-TPL-------------
--KRG---LPVGLPASALVANTALIEFDRIIEKEVVPLYYGRYVDDIILVLEN-------
------------------------------------------------------------
---------
>WP_009286519.1_132_297_UG5_
-------------------------------DQLSQNIYGSRLRRTIDNEVNEFSLGSFK
SYLKPFSDWRDGAIKTMRTALDDKK-KVLALTADVSSFYHRLHPK-----FMLS------
EAFQ-EIA--SVE-LDQ----EQRKLHQLFINAL---IAWAKG-TPL-------------
--KTG---LPVGLPASAVVANAALIGLDQFIERQVVPLYYGRYVDDVLLVMENS---SNI
QT----------------------------------------------------------
---------
>KMU71029.1_171_306_UG5_
------------------------------------------------------------
PYLKPFRDWRDGAIKAMRSALADKK-DVIALTADVSSFYHHLNPD-----FMLN------
ATFH-QKA--GIEQFDE----HATRLNQLFIGAL---QAWAKS-TPL-------------
--QKG---LPVGLPASAVVANAALIELDQFINKQVVPLYYGRYVDDILLVMHNT---SKL
------------------------------------------------------------
---------
>WP_058182825.1_162_308_UG5_
--------------------------------------------------LNKMALGSFK
PYLKPFRDWRNGAIKSMRSALEDKK-KVIALTADVTSFYHALNPS-----FMLD------
PTFQ-QLA--RVQ-LSE----PQDKLHKLFINAL---LVWAKN-TPL-------------
--KKG---LPVGLPASAVVANAALIQLDQFIERQVVPLYYGRYVDDILLVMENA---SNL
ST----------------------------------------------------------
---------
>WP_098950343.1_111_302_UG5_
----FRLMARCSIDFHVLSSLWMMEVGDLFDKQLSSNVFGSRLRRNRHDEISTWALGSFK
PYLRPFRKWRDGGIKAMRTALSEKK-KVLALTADVSSFYHELNPG-----FMLD------
DGFL-KLA--KIE-LSE----SQSKLNRLFISAL---LAWAQE-TPL-------------
--GKG---LPVGLPASAVVANAALIGLDQFIEQQVVPLYYGRYVDDILLVMENA---SDI
K-----------------------------------------------------------
---------
>WP_056840940.1_105_299_UG5_
PTAEFRLMAQCSMDFHTLSTLWMMEVGDLFDKVLGDNIYGSRLRRNRLHQINKLALGSFK
PYLKPFRDWRDGGIKAMRSALADNK-KVLALTADVSSFYHELNPD-----FMLD------
ENFL-SLA--EIE-LNS----TQAKLHRLFIGAL---KIWAKK-TPL-------------
--GKG---LPVGLPASAIVANSALLRLDQFIEQQVVPLYYGRYVDDIMLVMENT---SNI
------------------------------------------------------------
---------
>WP_096137967.1_106_302_UG5_
-IAEFRLMAQCSMDFHVLSALWMMEVGDLFDKTLGENVYGSRLRRNRSEQINKLALGSFK
PYLKPFRDWRDGGIKAMRSALGDKK-KVLALTADVSSFYHELNPE-----FMLD------
ERFL-SFA--GVK-LSK----NQKKLHRVFIGAL---QAWSKN-TPL-------------
--GKG---LPVGLPASAVVANSALLRLDQFIEKQVVPLYYGRYVDDVLLVMENT---SNI
KTT---------------------------------------------------------
---------
>OEU51672.1_184_331_UG5_
------------------------------------------------------------
-------------------ALDDKK-KIVAITADVSSFYHELNPD-----FMLN------
EEFL-GIL--GLEQLSP----DEKNFTRVFIQAL---KNWAKS-TPL-------------
--KKG---LPVGLPASAIVANMALVELDFYIQKEVVPLYYGRYVDDIILVMENG---ADF
SSTEEVWEWLFARSNNLLNWKDDKKEIVSFS-----------------------------
---------
>WP_091136693.1_180_293_UG5_
------------------------------------------------------------
------------------TALAAKK-KVISLTADVSSFYHELNPS-----FMLN------
EKFK-QLL--ELE-LKP----EEEKLNRLFIAAL---KEWAKR-TPL-------------
--EKG---LPVGLPASAVVANVALFELDQLIEQQVAPLYYGRYMDDILLVMENG------
------------------------------------------------------------
---------
>WP_059169679.1_166_315_UG5_
---------------------------------------------QDDKQINPLSLGSFK
PYLKPFRDWRDHGIRAMRSALNDKK-KIVALTADVSSFYHELNPC-----FMLD------
DDFISGVL--GLT-LSE----EQTKLNRLFINAL---SAWSAT-TPL-------------
--QRG---LPVGLPASAVVANMALVELDRIIAEQVAPIHYGRYVDDIILVMENG---AR-
------------------------------------------------------------
---------
>WP_014989234.1_181_304_UG5_
------------------------------------------------------------
--------WRDNGIQAMRNALHAGK-KIVAITADVSSFYHELNPG-----FMLD------
PGFMTEVV--GLE-LTE----TKAKLNRLFINGL---QAWAAN-TPL-------------
--KKG---LPVGLPAAAVVANVALLELDRVLEGQVVPLYYGRYVDDVMLVLEN-------
------------------------------------------------------------
---------
>OYY74881.1_193_307_UG5_
------------------------------------------------------------
--------------------LEANK-KVISLTADVSSFYHQISPS-----FMLD------
NRFI-KIL--NLD-LSP----QEEKLNRLFVMAL---EAWAKC-TPL-------------
--KKG---LPVGLPASAVVANMALIELDRFVEQQVVPLYYGRYVDDILLVMENG---AKF
------------------------------------------------------------
---------
>WP_046049600.1_181_308_UG5_
------------------------------------------------------------
-------DWRDNGISSMRTALDSNK-KIVALTADVSSFYHELKPS-----FMLE------
SSFLDDVL--SLD-LSE----SEKKLNRLFIKAL---EAWAAS-TPL-------------
--KKG---LPVGLPASAVVANMALIELDRVIEQQVVPLYYGRYVDDILLVMENG---AH-
------------------------------------------------------------
---------
>WP_059874130.1_193_311_UG5_
------------------------------------------------------------
--------------------LDVGK-KIVALTADISSFYHELNPV-----FMLN------
PVFVTGVL--GLE-MTA----DQVKLHRMFIQAL---LAWAAA-TPL-------------
--KKG---LPVGLPASAVVANVALAELDRIVEQECAPLYYGRYVDDILLVMENT---SGF
RSA---------------------------------------------------------
---------
>WP_075304188.1_143_308_UG5_
-----------------------------DAKLTDSACGNRLRRTRDRKKINPLSLGSFV
PYLKPFREWRDQGINAMRTALDADK-RIVALTADIGSFYHELNPD-----FMLD------
STFVNEVL--RLD-LSD----AEKKLNRLFIGAL---KRWAAA-TPL-------------
--KKG---LPVGLPASAVVANMALIELDRFVEQQIAPLYYGRYVDDILLVMENG---RD-
------------------------------------------------------------
---------
>WP_023301376.1_156_309_UG5_
------------------------------------------RRTLDGKDINALSIGSFQ
PYLRPFRDWRDNGINAMRSALSESK-KIVALTADVSSFYHELNPG-----FMLD------
PTFVKDIL--ELE-LTA----EQSKLNRLFINAL---KAWAIE-TPL-------------
--KKG---LPVGLPASAVVANVALIELDRVIEQQVAPIYYGRYVDDIILVMENG---ANF
------------------------------------------------------------
---------
>WP_090543058.1_168_346_UG5_
-------------------------------------------------------LGSFQ
PYLKPFRDWRDNGIAAMRAALDADK-KIVALTADVSSFYHELNPG-----FMLA------
SAFVTEVL--GLV-LTE----NQTKLNRLFIRAL---QAWAAA-TPL-------------
--KKG---LPVGLPASAVVANIALLELDRCIEQQVAPIYYGRYVDDILLVMENG---SDF
GSTVELWEWLFARADGKLGWVEAEKKQQICFKPDYLNH----------------------
---------
>OGT94063.1_190_313_UG5_
------------------------------------------------------------
----------------MRTALDAGK-KIVALTADVSSFYHKLNPG-----FMLN------
PVFVKGVL--GLD-LSD----EQAKLNRLLIQAL---QTWAAA-TPL-------------
--KNG---LPVGLPASAVVANVALVELDRIVEQQVAPLYYGRYVDDILLVMENG---ADF
RSTV--------------------------------------------------------
---------
>CDI94624.1_170_307_UG5_
---------------------------------------------------------SFQ
PYLKPFRDWRDQGIEAMRTALNADK-KIVALTADVSSFYHELNPG-----FMLN------
PAFVVDVL--GLE-LSP----AQSKLHRLFIQAL---QAWAAA-TPL-------------
--KKG---LPVGLPASAVVANVALIELDRVVEQQIAPLYYGRYVDDILLVMESG---AS-
------------------------------------------------------------
---------
>WP_050595161.1_196_325_UG5_
------------------------------------------------------------
-----------------KEMLSEGK-NVTAVTMDITRFYHRVSAK-----FILR------
PAFL-KSI--HVT-LDI----NEKTFTKMLIESF---DAWYAE-TPD----------VKN
RPEGC---LPVGLTASKVISNILLYELDIQISESIATTYYGRYVDDLFIVFETP---KDL
INGNEIV-----------------------------------------------------
---------
>WP_012197556.1_203_340_UG5_
------------------------------------------------------------
----------------MKKLISEGH-DVTAITMDLAGFYHNASPN-----FLLR------
PSFL-RKL--GLS-LSS----DERKFTRLILESI---NNWYLT-TPD----------YEQ
RTDGA---LPVGSSISKIISNVLLYELDKQISEGLEPEYYGRYVDDIFLVFKTP---DEE
LTGDSILSHMSKHV----------------------------------------------
---------
>WP_090175189.1_177_292_UG5_
------------------------------------------------------------
------------------------------VTMDIRRFYHNVSPT-----FLLA------
PEFM-EVC--GVH-LSE----DQRLFTQDFIESI---QNWYRR-TPD----------AKV
RPEGG---LPVGLSASKIISNLVLVEFDRLIQKKLKPIYYGRYVDDLFLVCSRD---AGI
SSGRD-------------------------------------------------------
---------
>WP_013232091.1_173_327_UG5_
---------------------------------------------------------LFA
PYFSAYRKWRETGLNRMEESLKQGK-DILAITMDLEQFYHRVAPT-----FLLR------
KSFL-QSI--RLK-LTT----FERQFTTDLLDAI---ALWYEQ-TPD----------FKV
RPQGA---LPVGLSASKIISNVLLANFDNAILQKIKPIYYGRYVDDIFLVFENT---KLA
VNAKEVTQRIAK------------------------------------------------
---------
>WP_047212465.1_203_326_UG5_
------------------------------------------------------------
---------------------EVGK-SILAITMDVEKFYHRVSPK-----FLLR------
KAFL-ESV--GIA-LTS----AEKRFTERLLEAI---STWYQS-TPD----------YVH
RPAGA---IPVGLSASKIIANILLADFDRAVVANLKPLYYGRYVDDIFLVLDSI---GED
HSAQR-------------------------------------------------------
---------
>WP_007184993.1_193_320_UG5_
------------------------------------------------------------
----------------MEGALNEGK-SILAITMDVEQFYHRVSPD-----FLLK------
KSFL-ESQ--RIE-LST----AQRRFTKQLLTAI---GTWYKK-TPD----------FRT
RPEGA---IPVGLSASKIIANVLLADFDYAVTDKLKPIYYGRYVDDVFLVLETA---EES
SGGA--------------------------------------------------------
---------
>WP_093095636.1_184_326_UG5_
------------------------------------------------------------
---------------------KEDK-NVLVITSDLKKYYHSIEIS--ELRFKVD------
-----KLI--KKHSFNK----TDLFINELLFQMI---EHFNDLNNKNYQDFFDSNINNLD
NKNFG---LPLTLNASRVLANIYLLDFDQDIIDNLKPLYYGRYVDDLIIAVEYS---GYT
NDQLCLKDILKPL-----------------------------------------------
---------
>CUO77905.1_180_308_UG5_
------------------------------------------------------------
-----------VVNNNSNNDEDNNK-SVILTMLDLSRYYYNIEIT-----EKIF------
EKMTNTFY--DNKDDSL------NRLNYCVYDIM---KKYSEL-CGCDKEYM--------
--------LPIGFLPSSIISNYYLKDIDEKMSKSKGGVYYGRYVDDMILVTQIE-NWDDL
K-----------------------------------------------------------
---------
>WP_077869186.1_167_298_UG5_
------------------------------------------------------------
--------WRDDAVNLVEKRMDDKK-RTIMMSLDVKEYFYSTNID-----FKNKF-----
NDEIKAII--KKKNASYTRRKAYEKINNFIEKVI---EKYSSE-ISK-------------
DKRNL---LPIGFLPSPILCNWYLKDFDTEVIKKINPLYYKRYIDDIILVFNG-------
------------------------------------------------------------
---------
>WP_057534979.1_199_332_UG5_
------------------------------------------------------------
--------------SSVEQMIKEEK-RCLMITLDIKDYFYTANIDFDKLKYDLLLVDSDK
DKYKDKNT--EDNIIKQ---NLKFIINDIVINIF---NKYTKIIKGR-------------
EDENI---IPIGFIPSYIICNWYLNEFDNQVIKELNPIYYGRYIDDITIVIPI-------
------------------------------------------------------------
---------
>ZP_02091461.1_UG5_156_315
----------------------------------------RKTLYNEFSKEPTFSPALFE
PYFQNYESWRDQALTLAQKCMQQD--DVLIFTLDFKRYYYSVDVS---------------
EEFMKEILT-GVKGKSDYNEEYLSRINDFVYCVI---KRYSQIYKEH---------SGEE
WIRRI---LPIGFLPSGVLANECLKKFDTAILDGWNPLYYGRYVDDILLVE---------
------------------------------------------------------------
---------
>WP_010993357.1_191_336_UG5_
------------------------------------------------------------
----------DNALNSATKLLDDNK-DATILSLDIQRYFYSVRID---------------
LDSIKNRCSHSNKQIEK-CFHLLQIINKTYTSKI---NKLLD--IPL----------TND
ELNAGYTILPIGLLSSGLLGNLYLEDFDKTIKEELNPAYYGRYVDDILFVFSDRKVKLEV
NNPIHDFI----------------------------------------------------
---------
>WP_085755544.1_182_385_UG5_
------------------------------------------------------------
-------------------LLNSKE-DVAILALDIEQFYYSIEFN-----FDKL------
KNCLNDKR--NDKDSKDEDISIAIKLTEIIEVIC---KRYNSK-IKHLKELT-----HPC
TSNNT---LPLGMNFSPILANWFISDFDKAIEKKINPEYYGRYVDDMLIVLANPTINEKD
SFKSFVHDYFIKTDILAEKDSKYVFKDNHNLRINDKKVLLQHFSKDHSQASLEKFVNKIK
QNSSEFRYL
>WP_096044623.1_171_294_UG5_
------------------------------------------------------------
-------------LEEIEYLISKEK-EVIVLCLDIKDYYYSVDIK-----LKDL------
EEDILSIY--PQFKEDK----KSKVLNDYIYEII---KNYSEKVMKK-------------
SEKTM---LPIGFLPSNIIANWYLKKFDNKILNKLNPAYYGRYVDDILIVIPQY------
------------------------------------------------------------
---------
>ZP_02130561.1_UG5_178_302
------------------------------------------------------------
--------------DKAKKALENGT-DIMIIGLDIMQCYYHIKVD-----WNSI------
EAVVANDYF-GMS-LCT----ILKRISTKYIKKL---RKNTEITHPT-----------VM
AEDEG---LPIGLSSSGIIANWALNIFDQAVRSKLSPLYYGRYVDDILIVLQ--------
------------------------------------------------------------
---------
>CUP79502.1_129_311_UG5_
----------------------------------------------RIRNINDSTVSLFK
PYYNNYSNWRDFGIKAIENRLKDDK-SVVYISMDIKDYYYSIDMNNEEVGF---------
DNLIKELTNYYND-EKE----LIVGLTEIIKKIC---TKYSSKIITN-------------
--RRC--ILPIGFIPSSILSNWYLKDFDKSIVEEINPIYYGRYVDDIILVCNIY---NTR
KTKEEIIDKYLIKPKILKRNSKKRLQV---------------------------------
---------
>YP_001030367.1_UG5_129_201
------------------------------------------------------------
---------------------------------RIHEKYFEIVKN-----YISV------
---------------------TNRTIKDREINKF--------------------------
--------LPIGLFSSGILANWHLKEFDKAVIKDVSPRYYGRYVDDCIFVF---------
------------------------------------------------------------
---------
>WP_091980546.1_188_340_UG5_
------------------------------------------------------------
-----------------------GD-NVAVVALDIKQYFYNIDLK-----FQKI------
TAEIESLI--DDKEALE----LALFLTNLLEKIY---KEYREKIKPQ-----LKYTHKGC
ENNVG---LPIGLTSSTVLANWYLSGFDREVSDIVRPAYYGRYVDDILFVFKRP---KLQ
QT---KVVKSFIEDYLSSAISIEDKKFEVIS-----------------------------
---------
>ZP_01889761.1_UG5_185_294
------------------------------------------------------------
------------------------DIDVVILSIDIKEYYYNINID---------------
KVFQDKLSKDIKGSLNK----RKLFFTDLLFDIM---RAYQKI-CPH-------------
DSNNI---LPIGLLSSGILANYYLKDFDEEIKSELAPAYYGRYVDDIQIVL---------
------------------------------------------------------------
---------
>WP_053009538.1_182_342_UG5_
------------------------------------------------------------
-------------NKAIEVVNTDNK-DVAIFSLDLKGFYYNIDID-----FNII------
SNIITETQNPKLIELSLILNDCLKKIHEKYKAVV---ENTIGI-THL------------K
NNNGG---IPIGMTSSAILSNWYLKKFDDDVEELINPIYYGRYVDDMIFVLKSP---KLE
FGNNKNAINDFISNILRGMIVESEKDKG--------------------------------
---------
>WP_052271646.1_179_326_UG5_
------------------------------------------------------------
------------IEKAIQEVEENDK-DVAILSLDLKGFYYNIKID-----FSKI------
SKFIDKS---QVNELLE----LSHFLNNKLEEIH---DKYNSI-ISDDLSIT-----HPH
LEHGG---IPIGFTSSAILANWHMINFDEDILKLLKPSYYGRYVDDILFVFTSP---EIG
EDNYGNEVSHFIKE----------------------------------------------
---------
>WP_075384215.1_183_322_UG5_
------------------------------------------------------------
---------------KAIDVVSKDKNDVAILSLDLKGFYYNIDIN-----FDTI------
NELINEKLDGERKDLALFLNEKLQLIHEKYHEVI---YELMKETHPS-------------
NTVLG---IPIGFTSSAILANWHLNKLDHDIISKLNPAYYGRYVDDIFLVFSRP---NID
GAEKGSEV----------------------------------------------------
---------
>WP_000623838.1_180_334_UG5_
------------------------------------------------------------
-------------NKAIDTVEKDQE-NVAILSIDLKSFYYNINID-----FKKI------
EKVIIDNSPSESMELSLYLNEKISQMHDMYKQII---APYICV-THE------------E
SVSKG---IPIGFTSSAILANWYLSDFDADIKSKINPAYYGRYVDDILFVFSSP---SIQ
PSEKGKEIINFIDSALGDFINH--------------------------------------
---------
>WP_061057569.1_179_325_UG5_
------------------------------------------------------------
--------------NKAIEVIEKDRNDVAILSLDLKGFYYNIYVD-----FDAI------
DALIEEH---QLEEIKE----LSLFLNKKLKLMH---EKYRNKISPFIEET------HPE
SASKG---IPIGFTSSAILANWYLANFDRDIKSKINPSYYGRYVDDILFVFSSP---KIE
IEDRGNEVVNFINR----------------------------------------------
---------
>WP_024228187.1_171_329_UG5_
------------------------------------------------------------
-----YNKWRDGGIDKAIEVIEKERNDVAILSLDLKGFYYNIDID-----FDAI------
DRIIDEEQLEEIKALSMLLNSKLRLMHQKYREKISPYIGVTHS-TPS-------------
--SKG---IPIGFTSSAILSNWYLMGFDKDIKSKINPSYYGRYVDDILLVFSSP---DIK
KEDKGEEVIKFIERTLN-------------------------------------------
---------
